credentials:

  # required configuration
  username: '1f53c607-9276-43ba-b539-b2786e5f6994'
  password: 'Phf9xjPtDvNA'

  # optional configuration
  name: "Personality Insights-xb"
  label: "personality_insights"
  plan: "IBM Watson Personality Insights Monthly Plan"
  url: "https://gateway.watsonplatform.net/personality-insights/api"
  
